#include <stdio.h>
#include <string.h>
struct book
{
    int page;
    float prices;
    char bookname[5];
};
int main()
{
struct book arr[10];
  printf("Enter the page number\n");
 scanf("%d",&arr[0].page);
 printf("Enter the prices number\n");
 scanf("%f",&arr[0].prices);
 printf("Enter the book name number\n");
scanf("%s",arr[0].bookname);
  printf("Enter the page number\n");
 scanf("%d",&arr[1].page);
 printf("Enter the prices number\n");
 scanf("%f",&arr[1].prices);
 printf("Enter the book name number\n");
scanf("%s",arr[1].bookname);
  printf("Enter the page number\n");
 scanf("%d",&arr[2].page);
 printf("Enter the prices number\n");
 scanf("%f",&arr[2].prices);
 printf("Enter the book name number\n");
scanf("%s",arr[2].bookname);
  printf("Enter the page number\n");
 scanf("%d",&arr[3].page);
 printf("Enter the prices number\n");
 scanf("%f",&arr[3].prices);
 printf("Enter the book name number\n");
scanf("%s",arr[3].bookname);
  printf("Enter the page number\n");
 scanf("%d",&arr[4].page);
 printf("Enter the prices number\n");
 scanf("%f",&arr[4].prices);
 printf("Enter the book name number\n");
scanf("%s",arr[4].bookname);
  printf("Enter the page number\n");
 scanf("%d",&arr[5].page);
 printf("Enter the prices number\n");
 scanf("%f",&arr[5].prices);
 printf("Enter the book name number\n");
scanf("%s",arr[5].bookname);
  printf("Enter the page number\n");
 scanf("%d",&arr[6].page);
 printf("Enter the prices number\n");
 scanf("%f",&arr[6].prices);
 printf("Enter the book name number\n");
scanf("%s",arr[6].bookname);
  printf("Enter the page number\n");
 scanf("%d",&arr[7].page);
 printf("Enter the prices number\n");
 scanf("%f",&arr[7].prices);
 printf("Enter the book name number\n");
scanf("%s",arr[7].bookname);
  printf("Enter the page number\n");
 scanf("%d",&arr[8].page);
 printf("Enter the prices number\n");
 scanf("%f",&arr[8].prices);
 printf("Enter the book name number\n");
scanf("%s",arr[8].bookname);
  printf("Enter the page number\n");
 scanf("%d",&arr[9].page);
 printf("Enter the prices number\n");
 scanf("%f",&arr[9].prices);
 printf("Enter the book name number\n");
scanf("%s",arr[9].bookname);
 printf("book page number: %d \n",arr[0].page);
 printf("book prices: %f\n",arr[0].prices);
 printf("book name:%s\n",arr[0].bookname);
 printf("book page number: %d \n",arr[1].page);
 printf("book prices: %f\n",arr[1].prices);
 printf("book name:%s\n",arr[1].bookname);
 printf("book page number: %d \n",arr[2].page);
 printf("book prices: %f\n",arr[2].prices);
 printf("book name:%s\n",arr[2].bookname);
 printf("book page number: %d \n",arr[3].page);
 printf("book prices: %f\n",arr[3].prices);
 printf("book name:%s\n",arr[3].bookname);
 printf("book page number: %d \n",arr[4].page);
 printf("book prices: %f\n",arr[4].prices);
 printf("book name:%s\n",arr[4].bookname);
 printf("book page number: %d \n",arr[5].page);
 printf("book prices: %f\n",arr[5].prices);
 printf("book name:%s\n",arr[5].bookname);
 printf("book page number: %d \n",arr[6].page);
 printf("book prices: %f\n",arr[6].prices);
 printf("book name:%s\n",arr[6].bookname);
 printf("book page number: %d \n",arr[7].page);
 printf("book prices: %f\n",arr[7].prices);
 printf("book name:%s\n",arr[7].bookname);
 printf("book page number: %d \n",arr[8].page);
 printf("book prices: %f\n",arr[8].prices);
 printf("book name:%s\n",arr[8].bookname);
 printf("book page number: %d \n",arr[9].page);
 printf("book prices: %f\n",arr[9].prices);
 printf("book name:%s\n",arr[9].bookname);
    return 0;
}